sudo: required
services: 
    - docker


before_install:
        - docker build -t amitabhajana/react-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true amitabhajana/react-docker npm run test


