sudo: required
services: 
    - docker


before_install:
        - docker build -t amitabhajana/docker-react -f Dockerfile.dev .

script:
    - docker run amitabhajana/docker-react npm run test -- --coverage
     